# Ref:  https://github.com/ansible/ansible-modules-core/issues/3423
#
#   Unable to use docker_image due to above referenced issue.
#
- name: pull etcd image
  shell: "docker pull {{ etcd_docker_image }}:{{etcd_docker_tag}}"

- name: create the etcd data dir on the docker host
  shell: mkdir -p "{{etcd_data_dir}}"

- name: run etcd container
  docker_container:
    name: etcd
    image: "{{ etcd_docker_image }}:{{ etcd_docker_tag }}"
    state: started
    detach: true
    recreate: true
    ports: "{{etcd_docker_ports}}"
    volumes: "{{etcd_docker_volumes}}"
    env:
      ETCD_NAME: "{{ etcd_name }}"
      ETCD_ADVERTISE_CLIENT_URLS: "{{ etcd_advertise_client_urls }}"
      ETCD_LISTEN_CLIENT_URLS: "{{ etcd_listen_client_urls }}"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "{{ etcd_initial_advertise_peer_urls }}"
      ETCD_LISTEN_PEER_URLS: "{{ etcd_listen_peer_urls }}"
      ETCD_INITIAL_CLUSTER: "{{ etcd_initial_cluster }}"
      ETCD_INITIAL_CLUSTER_TOKEN: "{{ etcd_initial_cluster_token }}"
      ETCD_INITIAL_CLUSTER_STATE: "{{ etcd_initial_cluster_state }}"
      ETCD_DATA_DIR: "{{ etcd_data_dir }}"
    restart_policy: always
  tags:
    - etcd
