- name: run etcd container
  docker:
    name: etcd
    image: "{{ etcd_image }}"
    state: reloaded
    detach: true
    ports:
    - "2380:2380"
    - "2379:2379"
    env:
      ETCD_NAME: "{{ etcd_name }}"
      ETCD_ADVERTISE_CLIENT_URLS: "{{ etcd_advertise_client_urls }}"
      ETCD_LISTEN_CLIENT_URLS: "{{ etcd_listen_client_urls }}"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "{{ etcd_initial_advertise_peer_urls }}"
      ETCD_LISTEN_PEER_URLS: "{{ etcd_listen_peer_urls }}"
      ETCD_INITIAL_CLUSTER: "{{ etcd_initial_cluster }}"
      ETCD_INITIAL_CLUSTER_TOKEN: "{{ etcd_initial_cluster_token }}"
      ETCD_INITIAL_CLUSTER_STATE: "{{ etcd_initial_cluster_state }}"
    restart_policy: always
  tags:
    - etcd

